### ISSUE TITLE
Errors Upon Opening the application with the new update

### ISSUE THREAD

**Issue by asphodelhoes** [Sebane1/FFXIVVoicePackCreator#7]
![image](https://user-images.githubusercontent.com/122509223/211981440-0452ae87-a093-4848-83d4-ed9cdc8a0bf2.png)

whenever i open the application, without even touching anything else, i get this error. Here's the error message.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at FFXIVVoicePackCreator.FilePicker.filePicker_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   at System.Windows.Forms.TabControl.UpdateTabSelection(Boolean updateFocus)
   at System.Windows.Forms.TabControl.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TabControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by Sebane1** [comment]
Looks like it was crashing because FFXIV wasn't open. I've released a fix for this,
